version: 0.0.0-ci-{build}
image: Ubuntu

pull_requests:
    do_not_increment_build_number: true
        
environment:
    NODEJS_VERSION: 12.16.3
    SONARCLOUD_AUTH_TOKEN:
        secure: WSZCNtuf3h9M4BxNiFQ7SQPwGkg3+LqSMZRyfYruiicYvc1BzYaN90n8pNEsPAKs
    DOCKER_HUB_ACCT: jeffwinn
    DOCKER_HUB_REPO: plex-transcoder
    DOCKER_HUB_AUTH_TOKEN:
        secure: Va78zuCPdE+yXdoAAcIhmF1nSP1IINHadv1boECCVAE82rzOQci8pN+sZrv+FYZz
    
stack: node $NODEJS_VERSION, docker

# See: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/ for the versions of the Sonar Scanner CLI that are available.

install:
    - npm install
    - sudo apt-get install unzip
    - sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-linux.zip
    - sudo unzip -q sonar-scanner-cli-4.3.0.2102-linux.zip -d /opt
    - sudo ln -s /opt/sonar-scanner-4.3.0.2102-linux/bin/sonar-scanner /usr/local/bin

before_build:
    - sudo sonar-scanner -Dsonar.login="$SONARCLOUD_AUTH_TOKEN"

build_script:
    - npm run build-prod

test_script:
    - npm run test
    
artifacts:
    - path: 'build'
      name: 'src'

    - path: 'test_results/coverage'
      name: 'test coverage'

    - path: 'test_results/jest-junit.xml'
      name: 'test results'

deploy_script:
    - ps: |
        $deploy = ($env:APPVEYOR_REPO_BRANCH -eq 'master' -or $env:APPVEYOR_REPO_BRANCH -eq 'develop')
        if (-not $deploy) {
            return
        }

        docker login --username="$env:DOCKER_HUB_ACCT" --password="$env:DOCKER_HUB_AUTH_TOKEN"        
        
        $IMAGE_TAG = $env:APPVEYOR_BUILD_VERSION
        if ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
            # Remove the CI build tag from the production release builds.
            $IMAGE_TAG = $env:APPVEYOR_BUILD_VERSION.substring(0, $env:APPVEYOR_BUILD_VERSION.indexof('-'))
        }
        
        docker build -t "${env:DOCKER_HUB_ACCT}/${env:DOCKER_HUB_REPO}:${IMAGE_TAG}" .
        sudo docker push "${env:DOCKER_HUB_ACCT}/${env:DOCKER_HUB_REPO}:${IMAGE_TAG}"

on_success:
    - ps: |
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./test_results/jest-junit.xml))