version: 1.0.0-ci-{build}
image: Ubuntu

pull_requests:
    do_not_increment_build_number: true

# branches:
#     only:
#         - master
#         - develop
        
environment:
    DOCKER_HUB_ACCT: jeffwinn
    DOCKER_HUB_REPO: plex-transcoder
    DOCKER_HUB_TOKEN:
        secure: Va78zuCPdE+yXdoAAcIhmF1nSP1IINHadv1boECCVAE82rzOQci8pN+sZrv+FYZz
    
stack: node 12.16.3, docker

install:
    - npm install

build_script:
    - npm run build-prod
    - docker build -t $DOCKER_HUB_REPO:$APPVEYOR_BUILD_VERSION .
    - docker save $DOCKER_HUB_REPO:$APPVEYOR_BUILD_VERSION --output $DOCKER_HUB_REPO.$APPVEYOR_BUILD_VERSION.tar

test_script:
    - npm run test

artifacts:
    - path: '**/*.tar'
    - name: 'image'

# deploy_script:
#     - docker login --username="$DOCKER_HUB_ACCT" --password="$DOCKER_HUB_TOKEN"
#     - sudo docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPO:$APPVEYOR_BUILD_VERSION