version: 1.0.0-ci-{build}
image: Ubuntu

pull_requests:
    do_not_increment_build_number: true
        
environment:
    DOCKER_HUB_ACCT: jeffwinn
    DOCKER_HUB_REPO: plex-transcoder
    DOCKER_HUB_ENCRYPTED_TOKEN:
        secure: Va78zuCPdE+yXdoAAcIhmF1nSP1IINHadv1boECCVAE82rzOQci8pN+sZrv+FYZz
    
stack: node 12.16.3, docker

install:
    - npm install

build_script:
    - npm run build-prod

test_script:
    - npm run test

artifacts:
    - path: 'build'
      name: 'src'

    - path: 'coverage'
      name: 'test coverage'

deploy_script:
    - ps: |
        # $deploy = ($env:APPVEYOR_REPO_BRANCH -eq 'master' -or $env:APPVEYOR_REPO_BRANCH -eq 'develop')
        # if (-not $deploy) {
        #     return
        # }

        docker login --username="$env:DOCKER_HUB_ACCT" --password="$env:DOCKER_HUB_ENCRYPTED_TOKEN"        
        
        $IMAGE_TAG = $env:APPVEYOR_BUILD_VERSION
        # if ($env:APPVEYOR_REPO_BRANCH -eq 'develop') {
            # Remove the CI build tag from the release builds.
            $IMAGE_TAG = $env:APPVEYOR_BUILD_VERSION.substring(0, $env:APPVEYOR_BUILD_VERSION.indexof('-'))
        # }
        
        docker build -t "${env:DOCKER_HUB_ACCT}/${env:DOCKER_HUB_REPO}:${IMAGE_TAG}" .
        # sudo docker push "${env:DOCKER_HUB_ACCT}/${env:DOCKER_HUB_REPO}:${IMAGE_TAG}"