version: 0.0.0-ci-{build}
image: Ubuntu
deploy: off

for:
-
    branches:
        only:
            - master

    deploy: on
-
    branches:
        only:
            - develop    
            
    deploy: on

environment:
    DOCKER_HUB_ACCT: jeffwinn
    DOCKER_HUB_REPO: plex-transcoder
    DOCKER_HUB_TOKEN:
        secure: Va78zuCPdE+yXdoAAcIhmF1nSP1IINHadv1boECCVAE82rzOQci8pN+sZrv+FYZz
    
stack: node 12.16.3, docker

install:
    - npm install

build_script:
    - npm run build-prod    

test_script:
    - npm run test

before_deploy:
    - docker build -t $DOCKER_HUB_ACCT/$DOCKER_HUB_REPO:$APPVEYOR_BUILD_VERSION .

deploy_script:
    - docker login --username=$DOCKER_HUB_ACCT --password=$DOCKER_HUB_TOKEN
    - sudo docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPO:$APPVEYOR_BUILD_VERSION