version: 1.0.{build}
image: Ubuntu

stack: node 12.16.3, docker

install:
    - npm install
    
build_script:
    - npm run build-prod

test_script:
    - npm run test

before_deploy:
    - docker build -t jeffwinn/plex-transcoder:$APPVEYOR_BUILD_NUMBER